version: '3.3'

services:

  database: 
    container_name: db 
    hostname: db 
    image: mysql 
    volumes: 
      - ./mysql:/var/lib/mysql 
    networks: 'testnet'
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports: 
      - '3306:3306'
    expose:
      - '3306'
    restart: unless-stopped 


  app:
    container_name: library_app
    hostname: library_app
    build: 
      context: ./src 
      dockerfile: Dockerfile 
    environment: 
      MYSQL_PASSWORD: 'root'
    volumes:
      - ./src/:/usr/src/app/

    depends_on:
      - database
    stdin_open: true
    tty: true
